name: 'build-test'

# rebuild any PRs and main branch changes
on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  # make sure build/ci work properly
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all

  # make sure the action works on a clean machine without building
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: example
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: [2.18.0, stable, beta, dev]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          sdk: ${{ matrix.sdk }}
      - run: dart pub get
      - run: dart analyze
      - run: dart run bin/example.dart
